baseInt = int(input("ใส่ค่าเลขฐานจำนวนเต็ม : "))
expInt = int(input("ใส่ค่ายกกำลังจำนวนเต็ม : "))
result = pow(baseInt, expInt)
print("ต่ายกกำลังของ", baseInt, "^", expInt, "=", result)
print()

baseFloat = float(input("ใส่ค่าเลขฐานจำนวนเต็ม : "))
expFloat = float(input("ใส่ค่ายกกำลังจำนวนเต็ม : "))
result = pow(baseFloat, expFloat)
print("ต่ายกกำลังของ", baseFloat, "^", expFloat, end="")
print("=",result, "->",round(result,2))
